CREATE DATABASE college;
CREATE DATABASE IF NOT EXISTS COLLEGE;
DROP DATABASE IF EXISTS COMPANY;

USE college;
CREATE TABLE student(
id INT PRIMARY KEY,
name VARCHAR(50),
age INT NOT NULL
);

INSERT INTO student VALUES(1, "VAISHNAVI", 23);
INSERT INTO student VALUES(2,"SWATI",27);

SELECT * FROM student;

SHOW DATABASES;
SHOW TABLES;

DROP TABLE student;
