CREATE DATABASE COMPANY;

USE COMPANY;

CREATE TABLE EMPLOYEE(
id INT PRIMARY KEY,
name VARCHAR(50),
salary INT
);

INSERT INTO EMPLOYEE VALUES(1, "ADAM",25000);
INSERT INTO EMPLOYEE VALUES(2,"CASEY",30000);
INSERT INTO EMPLOYEE VALUES(3,"RAM",40000);

SELECT *FROM EMPLOYEE;